export const GET_PEOPLE_DETAIL_REQUESTED = 'GET_PEOPLE_DETAIL_REQUESTED';
export const GET_PEOPLE_DETAIL_SUCCESS = 'GET_PEOPLE_DETAIL_SUCCESS';
export const GET_PEOPLE_DETAIL_FAILURE = 'GET_PEOPLE_DETAIL_FAILURE';

export const GET_MEMBER_SEARCH_REQUESTED = 'GET_MEMBER_SEARCH_REQUESTED';
export const GET_MEMBER_SEARCH_SUCCESS = 'GET_MEMBER_SEARCH_SUCCESS';
export const GET_MEMBER_SEARCH_FAILURE = 'GET_MEMBER_SEARCH_FAILURE';
