export const GET_MEMBER_DETAIL_REQUESTED = 'GET_MEMBER_DETAIL_REQUESTED';
export const GET_MEMBER_DETAIL_SUCCESS = 'GET_MEMBER_DETAIL_SUCCESS';
export const GET_MEMBER_DETAIL_FAILURE = 'GET_MEMBER_DETAIL_FAILURE';
export const GET_MEMBER_SEARCH_REQUESTED = 'GET_MEMBER_SEARCH_REQUESTED';
export const GET_MEMBER_SEARCH_SUCCESS = 'GET_MEMBER_SEARCH_SUCCESS';
export const GET_MEMBER_SEARCH_FAILURE = 'GET_MEMBER_SEARCH_FAILURE';
export const MEMBER_SEARCH_EMPTY = 'MEMBER_SEARCH_EMPTY';
export const SELECTED_MEMBER_DETAIL = 'SELECTED_MEMBER_DETAIL';
export const SORT_BY_MEMBER_DETAIL = 'SORT_BY_MEMBER_DETAIL';

export const GET_REFERRAL_MANAGEMENT_REQUESTED =
  'GET_REFERRAL_MANAGEMENT_REQUESTED';
export const GET_REFERRAL_MANAGEMENT_SUCCESS =
  'GET_REFERRAL_MANAGEMENT_SUCCESS';
export const GET_REFERRAL_MANAGEMENT_FAILURE =
  'GET_REFERRAL_MANAGEMENT_FAILURE';
export const GET_REFERRAL_MANAGEMENT_SEARCH = 'GET_REFERRAL_MANAGEMENT_SEARCH';
export const EMPTY_REFERRAL_SEARCH = 'EMPTY_REFERRAL_SEARCH';
export const EXTEND_REFERRAL = 'EXTEND_REFERRAL';
export const EXTEND_REFERRAL_SUCCESS = 'EXTEND_REFERRAL_SUCCESS';
export const EXTEND_REFERRAL_FAILURE = 'EXTEND_REFERRAL_FAILURE';

export const GET_SPECIALTY_LIST_REQUESTED = 'GET_SPECIALTY_LIST_REQUESTED';
export const GET_SPECIALTY_LIST_SUCCESS = 'GET_SPECIALTY_LIST_SUCCESS';
export const GET_SPECIALTY_LIST_FAILURE = 'GET_SPECIALTY_LIST_FAILURE';
export const GET_REFERRAL_PROVIDER_REQUESTED =
  'GET_REFERRAL_PROVIDER_REQUESTED';
export const GET_REFERRAL_PROVIDER_SUCCESS = 'GET_REFERRAL_PROVIDER_SUCCESS';
export const GET_REFERRAL_PROVIDER_FAILURE = 'GET_REFERRAL_PROVIDER_FAILURE';
