version: 0.2

phases:
  install:
    commands:
      - echo Installing ...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm run-script build-preprod
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/**/*
    - Dockerfile
    - buildscripts/preprod/buildspecDockerBuild.yml
    # - buildscripts/Pull_Container.sh
    # - appspec.yml